### ISSUE TITLE
Location of FileSystem

### ISSUE THREAD

**Issue by uhlhosting** [rhubarbgroup/redis-cache#422]
Our systems use a so called Fortification and it blocks access to writting to filesystem, unless excluded with a manifest.json .

My question is what location is specifically redis cache complains when he says :

<img width="343" alt="image" src="https://user-images.githubusercontent.com/6324047/221338790-245e6903-1e8c-475c-9281-900bb783aa05.png">

I would need a path or a file name to exclude to fully allow the Fortification to work. In format:

```
fortification:
  max:
    - file1
  min:
    - file1
    - object-cache.php
    - wp-content/uploads
```

Can you be more specific as to what location it refers as FileSystem?
